### ISSUE TITLE
Error Reports

### ISSUE THREAD

**Issue by Ar97x** [GrowthcraftCE/Growthcraft-1.7#131]
I'm opening this for eventual error reports that might come from the forum and for anyone that needs help with bugs. If you can help, feel free to coment here. This is the first one:

```
[22:47:03] [Client thread/DEBUG] [MCFrames/]: Enabling mod MCFrames
 [22:47:03] [Client thread/DEBUG] [FML/]: Found translations in ForgeRelocation-0.0.1.4-universal.jar [en_US]
 [22:47:03] [Client thread/DEBUG] [ForgeRelocation/]: Enabling mod ForgeRelocation
 [22:47:03] [Client thread/DEBUG] [FML/]: Found translations in ForgeRelocation-0.0.1.4-universal.jar [en_US]
 [22:47:03] [Client thread/DEBUG] [RelocationFMP/]: Enabling mod RelocationFMP
 [22:47:03] [Client thread/DEBUG] [MrTJPCoreMod/]: Enabling mod MrTJPCoreMod
 [22:47:03] [Client thread/DEBUG] [redgear_core/]: Enabling mod redgear_core
 [22:47:03] [Client thread/TRACE] [FML/]: Verifying mod requirements are satisfied
 [22:47:03] [Client thread/TRACE] [FML/]: All mod requirements are satisfied
 [22:47:03] [Client thread/TRACE] [FML/]: Sorting mods into an ordered list
 [22:47:03] [Client thread/ERROR] [FML/]: Mod Sorting failed.
 [22:47:03] [Client thread/ERROR] [FML/]: Visting node APIContainer{CoFHAPI:1.0}
 [22:47:03] [Client thread/ERROR] [FML/]: Current sorted list : [Dummy Container (BeforeAll) @2108554981, Wrapped{mcp}, Wrapped{FML}, Wrapped{Forge}, Wrapped{Dummy Container (null) @1062826950}, Wrapped{Aroma1997Core}, Wrapped{CodeChickenCore}, Wrapped{Dummy Container (null) @1800288316}, Wrapped{ivtoolkit}, Wrapped{MCVanillaTweaks}, Wrapped{MobiusCore}, Wrapped{NotEnoughItems}, Wrapped{OpenComputers|Core}, Wrapped{Dummy Container (null) @231818377}, Wrapped{TubesCore}, Wrapped{OpenModsCore}, Wrapped{<CoFH ASM>}, FMLMod:debug{1.0}, Dummy Container (Before) @1335446611]
 [22:47:03] [Client thread/ERROR] [FML/]: Visited set for this node : [APIContainer{CoFHAPI:1.0}, Wrapped{MCVanillaTweaks}, Wrapped{<CoFH ASM>}, Wrapped{CodeChickenCore}, Dummy Container (BeforeAll) @2108554981, Dummy Container (AfterAll) @750349296, Dummy Container (Before) @1335446611, Wrapped{Dummy Container (null) @1062826950}, Wrapped{MobiusCore}, Wrapped{ivtoolkit}, FMLMod:BuildCraft|Core{7.1.12}, FMLMod:Additional-Buildcraft-Objects{MC1.7.10-BC7release3.0.2}, Wrapped{Dummy Container (null) @1800288316}, Wrapped{Forge}, Wrapped{Dummy Container (null) @231818377}, Wrapped{mcp}, Wrapped{OpenComputers|Core}, Wrapped{OpenModsCore}, Wrapped{Aroma1997Core}, FMLMod:CoFHCore{1.7.10R3.0.3}, Wrapped{FML}, FMLMod:BuildCraft|Builders{7.1.12}, Dummy Container (After) @1062496828, Wrapped{NotEnoughItems}, FMLMod:debug{1.0}, Wrapped{TubesCore}]
 [22:47:03] [Client thread/ERROR] [FML/]: Explored node set : [Wrapped{Aroma1997Core}, Wrapped{MCVanillaTweaks}, Wrapped{FML}, Wrapped{<CoFH ASM>}, Wrapped{CodeChickenCore}, Dummy Container (BeforeAll) @2108554981, Dummy Container (Before) @1335446611, Wrapped{Dummy Container (null) @1062826950}, Wrapped{MobiusCore}, Wrapped{NotEnoughItems}, Wrapped{ivtoolkit}, Wrapped{Dummy Container (null) @1800288316}, Wrapped{Forge}, Wrapped{Dummy Container (null) @231818377}, FMLMod:debug{1.0}, Wrapped{mcp}, Wrapped{OpenComputers|Core}, Wrapped{OpenModsCore}, Wrapped{TubesCore}]
 [22:47:03] [Client thread/ERROR] [FML/]: Likely cycle is in : [APIContainer{CoFHAPI:1.0}, Dummy Container (AfterAll) @750349296, FMLMod:BuildCraft|Core{7.1.12}, FMLMod:Additional-Buildcraft-Objects{MC1.7.10-BC7release3.0.2}, FMLMod:CoFHCore{1.7.10R3.0.3}, FMLMod:BuildCraft|Builders{7.1.12}, Dummy Container (After) @1062496828]
 [22:47:03] [Client thread/ERROR] [FML/]: A dependency cycle was detected in the input mod set so an ordering cannot be determined
 [22:47:03] [Client thread/ERROR] [FML/]: The first mod in the cycle is APIContainer{CoFHAPI:1.0}
 [22:47:03] [Client thread/ERROR] [FML/]: The mod cycle involves
 [22:47:03] [Client thread/ERROR] [FML/]: APIContainer{CoFHAPI:1.0} : before: [redgear_core, emashercore, emasherdefense, gascraft, eng_toolbox, EnderTech, BuildCraft|Builders, BuildCraft|Transport, BuildCraft|Energy, BuildCraft|Silicon, BuildCraft|Robotics, BuildCraft|Core, BuildCraft|Factory, BuildCraft|Compat, minechem, Railcraft, StevesAddons, funkylocomotion, FloodLights, CoFHCore, MalCore, fluxedfeederunit, Forestry, enhancedportals, ExtraUtilities, simplyjetpacks, IC2NuclearControl, RouterReborn, EnderIO, bcadditions, Mariculture, MariTech], after: [CoFHCore]
 [22:47:03] [Client thread/ERROR] [FML/]: Dummy Container (AfterAll) @750349296 : before: [], after: []
 [22:47:03] [Client thread/ERROR] [FML/]: FMLMod:BuildCraft|Core{7.1.12} : before: [], after: [Forge@[10.13.2.1236,)]
 [22:47:03] [Client thread/ERROR] [FML/]: FMLMod:Additional-Buildcraft-Objects{MC1.7.10-BC7release3.0.2} : before: [], after: [Forge@[10.13.2.1208,), BuildCraft|Transport, BuildCraft|Energy, BuildCraft|Silicon, BuildCraft|Factory, BuildCraft|Builders, LiquidXP]
 [22:47:03] [Client thread/ERROR] [FML/]: FMLMod:CoFHCore{1.7.10R3.0.3} : before: [], after: [Forge@[10.13.3.1448,10.14)]
 [22:47:03] [Client thread/ERROR] [FML/]: FMLMod:BuildCraft|Builders{7.1.12} : before: [], after: [BuildCraft|Core@7.1.12]
 [22:47:03] [Client thread/ERROR] [FML/]: Dummy Container (After) @1062496828 : before: [], after: []
 [22:47:03] [Client thread/ERROR] [FML/]: The full error
 cpw.mods.fml.common.toposort.ModSortingException: There was a cycle detected in the input graph, sorting is not possible
 at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:190) ~[TopologicalSort.class:?]
 at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
 at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
 at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
 at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
 at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
 at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
 at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
 at cpw.mods.fml.common.toposort.TopologicalSort.topologicalSort(TopologicalSort.java:145) ~[TopologicalSort.class:?]
 at cpw.mods.fml.common.toposort.ModSorter.sort(ModSorter.java:133) ~[ModSorter.class:?]
 at cpw.mods.fml.common.Loader.sortModList(Loader.java:272) [Loader.class:?]
 at cpw.mods.fml.common.Loader.loadMods(Loader.java:493) [Loader.class:?]
 at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208) [FMLClientHandler.class:?]
 at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
 at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
 at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
 at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
 at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
 at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
 [22:47:03] [Client thread/DEBUG] [FML/]: Mod sorting data
 [22:47:03] [Client thread/DEBUG] [FML/]: Additional-Buildcraft-Objects(Additional Buildcraft Objects:MC1.7.10-BC7release3.0.2): ABO-MC1.7.10-BC7-release3.0.2.jar (required-after:Forge@[10.13.2.1208,);required-after:BuildCraft|Transport;required-after:BuildCraft|Energy;required-after:BuildCraft|Silicon;required-after:BuildCraft|Factory;required-after:BuildCraft|Builders;after:LiquidXP)
 [22:47:03] [Client thread/DEBUG] [FML/]: additionalpipes(Additional Pipes:4.7.0): additionalpipes-4.7.0.jar (after:BuildCraft|Transport[7.1.5,);after:BuildCraft|Silicon;after:BuildCraft|Transport;after:BuildCraft|Factory;after:LogisticsPipes)
 [22:47:03] [Client thread/DEBUG] [FML/]: AdvancedMachines(IC2 Advanced Machines Addon:1.1.6): AdvancedMachinesAS-1.7.10.jar (required-after:IC2@2.2.775)
 [22:47:03] [Client thread/DEBUG] [FML/]: AdvancedSolarPanel(Advanced Solar Panels:1.7.10-3.5.1): AdvancedSolarPanel-1.7.10-3.5.1.jar (required-after:IC2; after:gregtech_addon; after:AppliedEnergistics;)
 [22:47:03] [Client thread/DEBUG] [FML/]: ae2stuff(AE2 Stuff:0.5.0.56): ae2stuff-0.5.0.56-mc1.7.10.jar (required-after:appliedenergistics2;required-after:bdlib@[1.9.2.104,))
 [22:47:03] [Client thread/DEBUG] [FML/]: AgriCraft(AgriCraft:1.7.10-1.4.1): AgriCraft-1.7.10-1.4.1-1.7.10.jar ()
 [22:47:03] [Client thread/DEBUG] [FML/]: AncientWarfareAutomation(Ancient Warfare Automation:2.4.113-beta-MC1.7.10): ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar (required-after:AncientWarfare;after:CoFHCore;after:BuildCraft|Core)
 [22:47:03] [Client thread/DEBUG] [FML/]: AncientWarfare(Ancient Warfare Core:2.4.113-beta-MC1.7.10): ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar ()
 [22:47:03] [Client thread/DEBUG] [FML/]: AncientWarfareNEIPlugin(Ancient Warfare NEI Plugin:2.4.113-beta-MC1.7.10): ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar (required-after:AncientWarfare;after:NotEnoughItems)
 [22:47:03] [Client thread/DEBUG] [FML/]: AncientWarfareNpc(Ancient Warfare NPCs:2.4.113-beta-MC1.7.10): ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar (required-after:AncientWarfare)
 [22:47:03] [Client thread/DEBUG] [FML/]: AncientWarfareStructure(Ancient Warfare Structures:2.4.113-beta-MC1.7.10): ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar (required-after:AncientWarfare)
 [22:47:03] [Client thread/DEBUG] [FML/]: aobd(Another One Bites The Dust:2.8.4): AOBD-2.8.4.jar (required-after:Forge@[10.13.4.1448,);after:*)
 [22:47:03] [Client thread/DEBUG] [FML/]: appliedenergistics2(Applied Energistics 2:rv2-stable-10): appliedenergistics2-rv2-stable-10.jar (after:appliedenergistics2-core;required-after:Forge@[10.13.2.1291,))
 [22:47:03] [Client thread/DEBUG] [FML/]: Aroma1997CoreHelper(Aroma1997Core|Helper:1.0.2.15): Aroma1997Core-1.7.10-1.0.2.15.jar ()
 [22:47:03] [Client thread/DEBUG] [FML/]: AromaBackup(AromaBackup:0.0.0.5): AromaBackup-1.7.10-0.0.0.5.jar (required-after:Aroma1997Core)
 [22:47:03] [Client thread/DEBUG] [FML/]: Artifacts(Artifacts:1.1.2): Artifacts-1.1.2.jar ()
 [22:47:03] [Client thread/DEBUG] [FML/]: baublelicious(Baublelicious:1.0.4): Baublelicious-1.7.10-1.0.5.jar (required-after:Baubles@[1.0.1.4,);)
 [22:47:03] [Client thread/DEBUG] [FML/]: bcapiHolder(bcapiHolder:1.0): bcapi-6.0.x.jar (after:BuildCraft|Core;after:Forestry;after:railcraft;before:BinnieCore)
 [22:47:03] [Client thread/DEBUG] [FML/]: bdlib(BD Lib:1.9.3.107): bdlib-1.9.3.107-mc1.7.10.jar ()
 [22:47:03] [Client thread/DEBUG] [FML/]: BetterTitleScreen(Better Title Screen:1.7.10-1.1): BetterTitleScreen-1.7.10-1.1.jar (required-after:Forge@[10.12.2.1147,))
 [22:47:03] [Client thread/DEBUG] [FML/]: BiblioCraft(BiblioCraft:1.10.5): BiblioCraft[v1.10.6][MC1.7.10].jar ()
 [22:47:03] [Client thread/DEBUG] [FML/]: BiblioWoodsBoP(BiblioWoods Biomes O'Plenty Edition:1.9): BiblioWoods[BiomesOPlenty][v1.9].jar (after:BiblioCraft;after:BiomesOPlenty)
 [22:47:03] [Client thread/DEBUG] [FML/]: BiblioWoodsForestry(BiblioWoods Forestry Edition:1.7): BiblioWoods[Forestry][v1.7].jar (after:BiblioCraft;after:Forestry)
 [22:47:03] [Client thread/DEBUG] [FML/]: BiblioWoodsNatura(BiblioWoods Natura Edition:1.5): BiblioWoods[Natura][v1.5].jar (after:BiblioCraft;after:Natura)
 [22:47:03] [Client thread/DEBUG] [FML/]: BigReactors(Big Reactors:0.4.3A): BigReactors-0.4.3A.jar (required-after:Forge@[10.13.2.1291,);required-after:CoFHCore;after:ThermalExpansion)
 [22:47:03] [Client thread/DEBUG] [FML/]: Botany(Botany:2.0-pre14): binnie-mods-2.0-pre14.jar (after:BinnieCore)
 [22:47:03] [Client thread/DEBUG] [FML/]: BinnieCore(Binnie Core:2.0-pre14): binnie-mods-2.0-pre14.jar ()
 [22:47:03] [Client thread/DEBUG] [FML/]: ExtraBees(Extra Bees:2.0-pre14): binnie-mods-2.0-pre14.jar (after:BinnieCore)
 [22:47:03] [Client thread/DEBUG] [FML/]: ExtraTrees(Extra Trees:2.0-pre14): binnie-mods-2.0-pre14.jar (after:BinnieCore)
 [22:47:03] [Client thread/DEBUG] [FML/]: Genetics(Genetics:2.0-pre14): binnie-mods-2.0-pre14.jar (after:BinnieCore)
 [22:47:03] [Client thread/DEBUG] [FML/]: BiomesOPlenty(Biomes O' Plenty:2.1.0): BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar (after:Natura; required-after:Forge@[10.12.2.1147,))
 [
```

**Comment by Ar97x** [comment]
Damn, that was a big text, does GH have some kind of "spoiler" thing like Minecraft Forum?

**Comment by spannerman79** [comment]
No, but usually you can use markdown to clean the text up to be justified properly

**Comment by IceDragon200** [comment]
@Ar97x 

``` md
`` `
Le code block
`` `

Of course remove the space before the ` and it works
```

Use code blocks, or just toss it in a gist, everyone with a github account also has a [gist](https://gist.github.com/) account

**Comment by IceDragon200** [comment]
@Ar97x Also the report has nothing to do with Growthcraft :scream: 

Actually: here are your culprits, according to the logs

> `[22:47:03] [Client thread/ERROR] [FML/]: Likely cycle is in :`
> - [APIContainer{CoFHAPI:1.0}, Dummy Container (AfterAll) @ 750349296, 
> - FMLMod:BuildCraft|Core{7.1.12}, 
> - FMLMod:Additional-Buildcraft-Objects{MC1.7.10-BC7release3.0.2}, 
> - FMLMod:CoFHCore{1.7.10R3.0.3}, 
> - FMLMod:BuildCraft|Builders{7.1.12}, Dummy Container (After) @ 1062496828]
> 
> A dependency cycle was detected in the input mod set so an ordering cannot be determined
> 
> The first mod in the cycle is APIContainer{CoFHAPI:1.0}
> The mod cycle involves:
> - APIContainer{CoFHAPI:1.0} : 
>   - **before**: [redgear_core, emashercore, emasherdefense, gascraft, eng_toolbox, EnderTech, BuildCraft|Builders, BuildCraft|Transport, BuildCraft|Energy, BuildCraft|Silicon, BuildCraft|Robotics, BuildCraft|Core, BuildCraft|Factory, BuildCraft|Compat, minechem, Railcraft, StevesAddons, funkylocomotion, FloodLights, CoFHCore, MalCore, fluxedfeederunit, Forestry, enhancedportals, ExtraUtilities, simplyjetpacks, IC2NuclearControl, RouterReborn, EnderIO, bcadditions, Mariculture, MariTech], 
>   - **after**: [CoFHCore]
> - Dummy Container (AfterAll) @ 750349296 : before: [], after: []
> - FMLMod:BuildCraft|Core{7.1.12} : before: [], after: [Forge@[10.13.2.1236,)]
> - FMLMod:Additional-Buildcraft-Objects{MC1.7.10-BC7release3.0.2} : 
>   - **before**: [], 
>   - **after**: [Forge@[10.13.2.1208,), BuildCraft|Transport, BuildCraft|Energy, BuildCraft|Silicon, BuildCraft|Factory, BuildCraft|Builders, LiquidXP]
> - FMLMod:CoFHCore{1.7.10R3.0.3} : 
>   - **before**: [], 
>   - **after**: [Forge@[10.13.3.1448,10.14)]
> - FMLMod:BuildCraft|Builders{7.1.12} : 
>   - **before**: [], 
>   - **after**: [BuildCraft|Core@7.1.12]
> - Dummy Container (After) @ 1062496828 : 
>   - **before**: [], 
>   - **after**: []
> 
> ```
> ```

**Comment by Sunconure11** [comment]
Found this error while trying to set up a farm structure using Recurrent Complex:

http://pastebin.com/WqzZtCrT

**Comment by IceDragon200** [comment]
@Sunconure11 https://github.com/Alatyami/Growthcraft-1.7/commit/8d5ae3e88e50f9d96ae605b9bddcd4db82a03d43

Check #130 for test build

**Comment by Ar97x** [comment]
I'll tell the guy the best I understood, but I'm not sure if I got it all.

**Comment by Sunconure11** [comment]
Looks like the crash is happening on servers too.

http://pastebin.com/DiiCDKu4

**Comment by Sunconure11** [comment]
According to the logs, its happening on the serverside mainly, rather than the client. Maybe there is some bad code?

**Comment by IceDragon200** [comment]
@Sunconure11 A bad block, something that wasn't registered properly.

Based on the logs and how the code works, I create `ItemKey`s from Item/Block, for the Block, you need to fetch the Item for it, if the block has no Item, then its an invalid Block registration, this type of stuff crashes even NEI.

@Sunconure11 Can you test again (it will fail hard this time) https://github.com/Alatyami/Growthcraft-1.7/commit/947cf0ceaa4ea846d50d7cbe1b42699a6c16eae1

**Comment by Sunconure11** [comment]
I will test it this time.

**Comment by Sunconure11** [comment]
So, its intentionally meant to crash? So far, I have not crashed with that build.

**Comment by Sunconure11** [comment]
http://pastebin.com/ibf22VGw

wat

**Comment by IceDragon200** [comment]
@Sunconure11 
:scream:
After my epic speech and feeling awesome... _puts paper bag on head_

https://github.com/Alatyami/Growthcraft-1.7/commit/f4d34f447928f8c002958efa0659ef70393ddb68

**Comment by Sunconure11** [comment]
It works, as far as I can tell.

**Comment by Sunconure11** [comment]
Latest dev build might not be compatible with Ars Magica 2:

http://pastebin.com/nhXF4Fkb

**Comment by IceDragon200** [comment]
@Sunconure11 ._. nope, that's just my development code leaking...

```
java.lang.NullPointerException: Initializing game
        at am2.blocks.BlockAMOre.func_149666_a(BlockAMOre.java:72)
        # \/ That's the registry dumper for debugging, its not suppose to run normally
        at growthcraft.core.util.GameRegistryDumper.dumpBlocks(GameRegistryDumper.java:37)
        at growthcraft.core.util.GameRegistryDumper.run(GameRegistryDumper.java:94)
```

**Comment by IceDragon200** [comment]
@Sunconure11 Fixed in the latest build, be sure to check it :3

**Comment by Sunconure11** [comment]
I will in a bit.

**Comment by Ar97x** [comment]
"the bamboo leaves despawn even if placed by a player so they cant really be used creatively" from lunchboxxx19. Anyone willing to give it a fix?

**Comment by IceDragon200** [comment]
@Ar97x right, lemme look into that, also, are bamboo leaves the only one giving trouble, do Apple Leaves behave correctly?

EDIT:
I just tested, it works fine here (using development build)

**Comment by Ar97x** [comment]
I'll ask the guy.

**Comment by Ar97x** [comment]
He said apple leaves behave the same way. Any thought of what it could be?

**Comment by IceDragon200** [comment]
@Ar97x Ask him to test the mod by itself, if the problem persists then I have no idea what's going on.
On the other hand, he may have something like Fast Decay, or some other mod that affects Leaves

**Comment by Ar97x** [comment]
My thought was on that, but I don't know if Fast Leaf Decay despawns leaves
placed by players.

**Comment by Sunconure11** [comment]
I tried to open the search tab in the creative menu and got this crash:

http://pastebin.com/AYrRpMDA

**Comment by IceDragon200** [comment]
@Sunconure11 Ah, my temp list has backfired, I'll fix that

EDIT:
https://github.com/GrowthcraftCE/Growthcraft-1.7/issues/183

The latest build should fix that issue

**Comment by Ar97x** [comment]
Error from the forum:
"I have with the Version growthcraft-1.7.10-2.4.0-complete this warning at Client (forge 10.13.4.1566) Startup:"

[14:35:18] [Client thread/INFO] [STDERR]: [growthcraft.cellar.GrowthCraftCellar:registerPotions:280]: Severe error, please report this to the mod author:
[14:35:18] [Client thread/INFO] [STDERR]: [growthcraft.cellar.GrowthCraftCellar:registerPotions:281]: java.lang.ArrayIndexOutOfBoundsException

[14:35:18] [Client thread/WARN] [FML]: ****************************************

[14:35:18] [Client thread/WARN] [FML]: \* A broken ore dictionary registration with name foodApplejuice has occurred. It adds an item (type: class growthcraft.cellar.common.item.ItemBoozeBottle) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.

TO USERS: YES this is a BUG in the mod Growthcraft Apples report it to them!

[14:35:18] [Client thread/WARN] [FML]: \* at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)

[14:35:18] [Client thread/WARN] [FML]: \* at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)

[14:35:18] [Client thread/WARN] [FML]: \* at growthcraft.apples.GrowthCraftApples.register(GrowthCraftApples.java:113)

[14:35:18] [Client thread/WARN] [FML]: \* at growthcraft.apples.GrowthCraftApples.preload(GrowthCraftApples.java:87)

[14:35:18] [Client thread/WARN] [FML]: \* at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[14:35:18] [Client thread/WARN] [FML]: \* at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...

[14:35:18] [Client thread/WARN] [FML]: ****************************************

**Comment by spannerman79** [comment]
> A broken ore dictionary registration with name foodApplejuice has occurred. It adds an item (type: class growthcraft.cellar.common.item.ItemBoozeBottle) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.

Yeah... don't feel left out as many other mods needed to make that change :frowning:

**Comment by IceDragon200** [comment]
@Ar97x  @spannerman79 I believe I fixed that in development already. https://github.com/GrowthcraftCE/Growthcraft-1.7/pull/180

The register potions one, now that is not something you see everyday, have the user check all their potion ids.

I always cringed at that potion hack we had though.

**Comment by Sunconure11** [comment]
http://pastebin.com/r0fq5aE3

Edit: Appears to be related to the refactoring of heat sources, I am altering my configs now.

**Comment by IceDragon200** [comment]
@Sunconure11 Yeah, just copy over the default config, I'm changing the config structures

``` json
{
  "comment": "Default heat sources",
  "data": [
    the_original_content
  ]
}
```

**Comment by Ar97x** [comment]
I found a bug on rice growing, pay attention at the textures and progress on Waila from the screenshots. 
![2016-01-31_01 55 11](https://cloud.githubusercontent.com/assets/10781341/12704527/42164d52-c844-11e5-864f-45e2dd616a72.png)
![2016-01-31_01 55 05](https://cloud.githubusercontent.com/assets/10781341/12704530/48d3d4b6-c844-11e5-956e-b6afc2524bcc.png)

**Comment by PitchBright** [comment]
@Ar97x does that happen, when only GC is installed with no other mods?

Also… does it happen 100% of the time, or just seemingly arbitrarily?

**Comment by Ar97x** [comment]
I haven't tried it without other mods. But it happens all the time, not
arbitrarily.
EDIT: It happens even without other mods. 100% chance

**Comment by IceDragon200** [comment]
@Ar97x Fixed in the latest grcmilk builds (10+)

**Comment by Sunconure11** [comment]
Milk needs an emergency hotfix.

http://pastebin.com/7KN74SKS

**Comment by PitchBright** [comment]
What were you crafting?

**Comment by Sunconure11** [comment]
This happened upon bootup.

**Comment by PitchBright** [comment]
K I think Dragon's already on it.

**Comment by IceDragon200** [comment]
@Sunconure11 @PitchBright Sorry, I did not test the builds, too much stuff going on D;

**Comment by IceDragon200** [comment]
Alright, closing this, if you have an issue or an error report, OPEN AN ISSUE FOR IT.
It makes tracking easier and less hectic.
If you have multiple issues or problems, and they don't have anything in common "Bug present in bamboo, and the fishtrap doesn't do this", open different issues so we can properly explore each.
