### ISSUE TITLE
Bug: broken ore dictionary registration (ItemBoozeBottle)

### ISSUE THREAD

**Issue by HanatakeYurii** [GrowthcraftCE/Growthcraft-1.7#222]
Hi,

I found this minor bug in my log today:

[12:37:58] [Client thread/WARN]: ****************************************
[12:37:58] [Client thread/WARN]: \* A broken ore dictionary registration with name foodApplejuice has occurred. It adds an item (type: class growthcraft.cellar.common.item.ItemBoozeBottle) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Growthcraft Apples report it to them!
[12:37:58] [Client thread/WARN]: \*  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[12:37:58] [Client thread/WARN]: \*  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[12:37:58] [Client thread/WARN]: \*  at growthcraft.apples.GrowthCraftApples.register(GrowthCraftApples.java:113)
[12:37:58] [Client thread/WARN]: \*  at growthcraft.apples.GrowthCraftApples.preload(GrowthCraftApples.java:87)
[12:37:58] [Client thread/WARN]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:37:58] [Client thread/WARN]: \*  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
[12:37:58] [Client thread/WARN]: ****************************************

**Comment by IceDragon200** [comment]
@HanatakeYurii Are you using the release build for 2.4.0?
If so that's an old bug, try one of our development builds instead.

Found here: https://github.com/GrowthcraftCE/Growthcraft-1.7/issues/200

There is a warning inside, don't use the dev builds in your actual game worlds, since they are unstable and I won't guarantee compatibility across builds

**Comment by HanatakeYurii** [comment]
Oh thx, I will try that. Yes I'm using the 2.4.0 relaease build. I suppose it will not happen on dev builds.

_Some minutes later, testing dev build_
Yes not happening anymore
Sorry for bothering
