### ISSUE TITLE
Crash with 60880a1 hanging cheese curds

### ISSUE THREAD

**Issue by gchpaco** [GrowthcraftCE/Growthcraft-1.7#271]
I made some gorgonzola cheese curds running on a SMP server running 60880a1 and hung them up and the server crashed.  Attached is the crash report; the relevant portion is 

``` java
java.lang.NoSuchFieldError: animPulsar
        at growthcraft.milk.common.tileentity.TileEntityHangingCurds.<init>(TileEntityHangingCurds.java:59)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at java.lang.Class.newInstance(Class.java:442)
        at growthcraft.core.common.block.GrcBlockContainer.func_149915_a(GrcBlockContainer.java:348)
        at net.minecraft.block.Block.createTileEntity(Block.java:1446)
```

since the code in question is

``` java
// the following variables are responsible for step tracking
   /// This pulse stepper is used to control the 'drip' animation
   @SideOnly(Side.CLIENT)
   private PulseStepper animPulsar = new PulseStepper(10, 4);
```

I'm guessing it wasn't completely moved off the server side or something.

[crash-2016-03-18_23.04.27-server.txt](https://github.com/GrowthcraftCE/Growthcraft-1.7/files/180672/crash-2016-03-18_23.04.27-server.txt)

**Comment by gchpaco** [comment]
FWIW: if I try to log in after said crash, I get kicked out immediately with the following traceback on the server:

``` java
[01:03:52] [Server thread/ERROR] [FML]: There was a critical exception handling a packet on channel Waila
java.lang.NoSuchFieldError: animPulsar
        at growthcraft.milk.common.tileentity.TileEntityHangingCurds.<init>(TileEntityHangingCurds.java:59) ~[TileEntityHangingCurds.class:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_65]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_65]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_65]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_65]
        at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_65]
        at growthcraft.core.common.block.GrcBlockContainer.func_149915_a(GrcBlockContainer.java:348) ~[GrcBlockContainer.class:?]
        at net.minecraft.block.Block.createTileEntity(Block.java:1446) ~[aji.class:?]
        at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850) ~[apx.class:?]
        at net.minecraft.world.World.func_147438_o(World.java:2540) ~[ahb.class:?]
        at mcp.mobius.waila.network.Message0x01TERequest.channelRead0(Message0x01TERequest.java:98) ~[Message0x01TERequest.class:?]
        at mcp.mobius.waila.network.Message0x01TERequest.channelRead0(Message0x01TERequest.java:27) ~[Message0x01TERequest.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]  
```

**Comment by IceDragon200** [comment]
@gchpaco Aha, dumb moment, it tries to initialize the animPulsar on the server since I gave it an initial value, some java stuff.

Should be fixed in the latest build https://github.com/GrowthcraftCE/Growthcraft-1.7/commit/47091bfe3fe25780d68ac534e9966fea220582d9

**Comment by Sunconure11** [comment]
Is this still present for @gchpaco, or can it be closed?

**Comment by gchpaco** [comment]
Waiting on server admin; will update ticket and close it if it is fixed.

**Comment by gchpaco** [comment]
Yup, that did it.  Thanks, guys!
