### ISSUE TITLE
Crash in SMP with a5d1749

### ISSUE THREAD

**Issue by gchpaco** [GrowthcraftCE/Growthcraft-1.7#273]
When attempting to start a SMP server with a5d1749, we got the following crash.

Relevant section appears to be

``` java
[20:20:25] [Server thread/ERROR] [FML]: Caught exception from Growthcraft|Bees
java.lang.NoSuchMethodError: net.minecraft.item.Item.func_150895_a(Lnet/minecraft/item/Item;Lnet/minecraft/creativetab/CreativeTabs;Ljava/util/List;)V
        at growthcraft.cellar.integration.ThaumcraftBoozeHelper.registerAspectsForBottleStack(ThaumcraftBoozeHelper.java:195) ~[ThaumcraftBoozeHelper.class:?]
        at growthcraft.bees.integration.ThaumcraftModule.integrate(ThaumcraftModule.java:113) ~[ThaumcraftModule.class:?]
        at growthcraft.core.integration.ModIntegrationBase.tryToIntegrate(ModIntegrationBase.java:142) ~[ModIntegrationBase.class:?]
        at growthcraft.core.integration.ModIntegrationBase.postInit(ModIntegrationBase.java:124) ~[ModIntegrationBase.class:?]
        at growthcraft.api.core.module.ModuleContainer.postInit(ModuleContainer.java:151) ~[ModuleContainer.class:?]
        at growthcraft.bees.GrowthCraftBees.postload(GrowthCraftBees.java:235) ~[GrowthCraftBees.class:?]
```

(which is then repeated for Rice, Hops, Grapes, Milk and Apples).  Notably this problem does not exist with 47091bf.

[crashlog.txt](https://github.com/GrowthcraftCE/Growthcraft-1.7/files/181159/crashlog.txt)

**Comment by domingothegamer** [comment]
I can confirm this problem as well.

**Comment by IceDragon200** [comment]
@gchpaco  @domingothegamer Could you give 638b7db a run and see if it's fixed?

**Comment by gchpaco** [comment]
Still no good.  Attached new crashlog, but looks similar to the old one.

[crashlog.txt](https://github.com/GrowthcraftCE/Growthcraft-1.7/files/181185/crashlog.txt)

**Comment by domingothegamer** [comment]
Same issue as well. Roughly the same log as gchpaco fortunately.

**Comment by SvEgiiVEteR** [comment]
me too
http://upaste.me/e6d224047de8d53ad

**Comment by IceDragon200** [comment]
@domingothegamer @gchpaco @domingothegamer Could you guys give the latest build a spin again, this time, this time I'm sure I fixed it.

Commit 7f278f1

**Comment by esotericist** [comment]
Okay, build 7f278f1 successfully loads on the server I admin for @gchpaco. I told him you guys would probably have a fix within twelve hours of us reporting the issue. :D

**Comment by domingothegamer** [comment]
Fixed! Everything is in working order. :D

**Comment by gchpaco** [comment]
Concur re: fix.
