### ISSUE TITLE
Brew Kettle cause game crash(2.6.1)

### ISSUE THREAD

**Issue by Microsoft6477** [GrowthcraftCE/Growthcraft-1.7#385]
when right click Brew Kettle,game will crash

mod version 2.6.1
forge version 10.13.4.1614
crash report:
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 50
    at java.util.Arrays$ArrayList.get(Unknown Source)
    at growthcraft.cellar.common.tileentity.TileEntityBrewKettle.receiveGUINetworkData(TileEntityBrewKettle.java:183)
    at growthcraft.core.common.inventory.GrcContainer.func_75137_b(GrcContainer.java:254)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147245_a(NetHandlerPlayClient.java:1156)
    at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:26)
    at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by IceDragon200** [comment]
Confirmed, fixing right this moment

@Microsoft6477 
https://github.com/GrowthcraftCE/Growthcraft-1.7/pull/386 
Could you try the preview build to confirm that this fix works?

**Comment by Microsoft6477** [comment]
preview build works well!
