### ISSUE TITLE
[2.6.3] Cannot craft honey buckets

### ISSUE THREAD

**Issue by darthvader45** [GrowthcraftCE/Growthcraft-1.7#415]
@IceDragon200  have no idea how to craft honey buckets as of the 2.6 release.  I've tried honey pot with water bucket, with empty bucket, with both, honey combs and water bucket, etc. and nothing seems to work.  Any help here?

**Comment by bloche1871** [comment]
I have a similar problem with the latest dev build by IceDragon200, where I cannot craft young mead buckets

**Comment by IceDragon200** [comment]
@darthvader45 Yep, all the honey container recipes were removed when we switched to the ShapelessMultiRecipes (which are fancy recipes that read off the fluid dictionary).

tl;dr fancy internal stuff we never properly tested

@darthvader45, @bloche14 A new test build is up, it should have some new recipes, there is an issue if you place too many items it still accepts it. (try placing 4 bottles of honey, 1 bucket of water and 1 empty bucket, you'll still get mead, though you only needed 3 bottles of honey)

**Comment by darthvader45** [comment]
Weird.  I figured it out, though, right-clicking a bucket on a beebox gives a bucket of honey.  I suppose bottles will give bottles of honey. So there's that.

@bloche14 Try crafting a bucket of honey with a water bucket and an empty bucket.  Works for me.

**Comment by bloche1871** [comment]
@darthvader45 I think we are playing a different build: I was using the latest dev build and it wasn't working.

@IceDragon200 I am now getting this crash with your latest build:

```

 Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 13/09/16 10:03 PM
Description: Initializing game

java.lang.RuntimeException: Invalid shapeless ore recipe: net.minecraft.item.ItemGlassBottle@66a8751a, net.minecraft.item.ItemGlassBottle@66a8751a, net.minecraft.item.ItemGlassBottle@66a8751a, growthcraft.api.core.fluids.TaggedFluidStacks@4d3bc8c8, 3xitem.grc.FoodBottleFluidHoney@0
    at net.minecraftforge.oredict.ShapelessOreRecipe.<init>(ShapelessOreRecipe.java:54)
    at growthcraft.bees.init.GrcBeesRecipes.postInit(GrcBeesRecipes.java:214)
    at growthcraft.api.core.module.ModuleContainer.postInit(ModuleContainer.java:151)
    at growthcraft.bees.GrowthCraftBees.postInit(GrowthCraftBees.java:216)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.minecraftforge.oredict.ShapelessOreRecipe.<init>(ShapelessOreRecipe.java:54)
    at growthcraft.bees.init.GrcBeesRecipes.postInit(GrcBeesRecipes.java:214)
    at growthcraft.api.core.module.ModuleContainer.postInit(ModuleContainer.java:151)
    at growthcraft.bees.GrowthCraftBees.postInit(GrowthCraftBees.java:216)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 3605223872 bytes (3438 MB) / 4225236992 bytes (4029 MB) up to 8520204288 bytes (8125 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xms4096m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 116 mods loaded, 115 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJ   mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJ   FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJ   Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJ   BugfixMod{2.5.0} [BugfixMod] (minecraft.jar) 
    UCHIJ   CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
    UCHIJ   NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
    UCHIJ   OpenComputers|Core{1.6.0.7-rc.1} [OpenComputers (Core)] (minecraft.jar) 
    UCHIJ   <CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
    UCHIJ   cuchaz.ships.core{1.7.10-1.0.3} [Ships Mod Core] (minecraft.jar) 
    UCHIJ   tickDynamic{0.1.5} [Tick Dynamic] (minecraft.jar) 
    UCHIJ   FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) 
    UCHIJ   CustomOreGen{1.2.24} [Custom Ore Generation] (CustomOreGen-1.7.10-1.2.24.jar) 
    UCHIJ   Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
    UCHIJ   HardLib{15.26.1a} [HardLib] (1.7.10-HardLib-15.26.1a.jar) 
    UCHIJ   OreFlowers{1.0.0} [Ore Flowers] (1.7.10-OreFlowers-4.0.1.jar) 
    UCHIJ   guilib{1.0.7.2} [GUI Library] (1.7.10_GuiLib-1.0.7.2.jar) 
    UCHIJ   act{0.0.4_1.7.10} [AdminCommandsToolbox] (AdminCommandsToolbox-0.0.4_dev16_1.7.10.jar) 
    UCHIJ   AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
    UCHIJ   AppleCore{1.3.2} [AppleCore] (AppleCore-mc1.7.10-1.3.2.jar) 
    UCHIJ   Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJ   Artifacts{1.1.3} [Artifacts] (Artifacts-1.1.3.jar) 
    UCHIJ   CoFHCore{1.7.10R3.1.3} [CoFH Core] (CoFHCore-[1.7.10]3.1.3-327.jar) 
    UCHIJ   asielib{0.4.5} [asielib] (AsieLib-1.7.10-0.4.5.jar) 
    UCHIJ   Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHIJ   Automagy{0.28.2} [Automagy] (Automagy-1.7.10-0.28.2.jar) 
    UCHIJ   babyanimals{1.7.10-2} [Baby Animals Model Swapper] (BabyAnimals-1.7.10-2.jar) 
    UCHIJ   BetterAchievements{0.1.0} [Better Achievements] (BetterAchievements-1.7.10-0.1.0.jar) 
    UCHIJ   BetterFoliage{2.0.14} [Better Foliage] (BetterFoliage-MC1.7.10-2.0.14.jar) 
    UCHIJ   betterquesting{1.0.155} [Better Questing] (BetterQuesting-1.0.155.jar) 
    UCHIJ   BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) 
    UCHIJ   BiomeTweaker{1.2.128} [BiomeTweaker] (BiomeTweaker-1.7.10-1.2.128.jar) 
    UCHIJ   Botania{r1.8-249} [Botania] (Botania r1.8-249.jar) 
    UCHIJ   butterflymania{1.3.2} [Butterfly Mania] (butterflymania-1.7.10-1.3.2.jar) 
    UCHIJ   Railcraft{9.12.2.0} [Railcraft] (Railcraft_1.7.10-9.12.2.0.jar) 
    UCHIJ   TwilightForest{2.3.8dev} [The Twilight Forest] (twilightforest-1.7.10-2.3.8dev.jar) 
    UCHIJ   chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
    UCHIJ   climatecontrol{0.6.beta57} [Climate Control] (ClimateControl-0.6.beta59.jar) 
    UCHIJ   ThermalFoundation{1.7.10R1.2.5} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.5-115.jar) 
    UCHIJ   ImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7.jar) 
    UCHIJ   craftarcanum{1.1.1} [Craft Arcanum] (CraftArcanum-1.1.1.jar) 
    UCHIJ   DeadlyWorld{1.0.2} [Deadly World] (DeadlyWorld-1.7.10-1.0.2.jar) 
    UCHIJ   DynamicLights{1.3.9} [Dynamic Lights] (DynamicLights-1.7.10.jar) 
    UCHIJ   DynamicLights_onFire{1.0.5} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) 
    UCHIJ   DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) 
    UCHIJ   DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) 
    UCHIJ   DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) 
    UCHIJ   DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) 
    UCHIJ   DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) 
    UCHIJ   DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) 
    UCHIJ   DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) 
    UCHIJ   DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) 
    UCHIJ   emobile{1.2.1} [E-Mobile] (E-Mobile-MC1.7.10-1.2.1.jar) 
    UCHIJ   Emotes{1.0} [Emotes] (Emotes 1.0.1.jar) 
    UCHIJ   Enchiridion{1.3} [Enchiridion] (Enchiridion 2-1.7.10-2.0.2a.jar) 
    UCHIJ   Enchiridion2{2.0.2a} [Enchiridion 2] (Enchiridion 2-1.7.10-2.0.2a.jar) 
    UCHIJ   etfuturum{@VERSION@} [Et Futurum] (Et.Futurum-1.5.5-spec.jar) 
    UCHIJ   exoticbirds{1.0} [Exotic Birds] (Exotic Birds 1.7.10 - 1.0.3b.jar) 
    UCHIJ   fairylights{1.4.0} [Fairy Lights] (fairylights-1.4.0-1.7.10.jar) 
    UCHIJ   fastleafdecay{1.4} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.4.jar) 
    UCHIJ   PaintingSelGui{1.7.2.0} [PaintingSelectionGui] (Forge_PaintingSelectionGuiv1.7.2.0.zip) 
    UCHIJ   forgeamidst{1.7.10-1.2-beta} [ForgeAmidst] (ForgeAmidst-1.7.10-1.2-beta.jar) 
    UCHIJ   gadomancy{1.0.7.2} [Gadomancy] (gadomancy-1.7.10-1.0.7.2.jar) 
    UCHIJ   ganyssurface{1.12.8} [Gany's Surface] (Ganys Surface-1.12.8.jar) 
    UCHIJ   Growthcraft{1.7.10-2.6.3} [Growthcraft] (growthcraft-1.7.10-2.6.3-complete--d923af5.jar) 
    UCHIJ   Growthcraft|Cellar{1.7.10-2.6.3} [Growthcraft Cellar] (growthcraft-1.7.10-2.6.3-complete--d923af5.jar) 
    UCHIJ   Growthcraft|Grapes{1.7.10-2.6.3} [Growthcraft Grapes] (growthcraft-1.7.10-2.6.3-complete--d923af5.jar) 
    UCHIJ   Growthcraft|Rice{1.7.10-2.6.3} [Growthcraft Rice] (growthcraft-1.7.10-2.6.3-complete--d923af5.jar) 
    UCHIJ   Growthcraft|Milk{1.7.10-2.6.3} [Growthcraft Milk] (growthcraft-1.7.10-2.6.3-complete--d923af5.jar) 
    UCHIJ   Growthcraft|Apples{1.7.10-2.6.3} [Growthcraft Apples] (growthcraft-1.7.10-2.6.3-complete--d923af5.jar) 
    UCHIJ   Growthcraft|Hops{1.7.10-2.6.3} [Growthcraft Hops] (growthcraft-1.7.10-2.6.3-complete--d923af5.jar) 
    UCHIE   Growthcraft|Bees{1.7.10-2.6.3} [Growthcraft Bees] (growthcraft-1.7.10-2.6.3-complete--d923af5.jar) 
    UCHIJ   Growthcraft|Fishtrap{1.7.10-2.6.3} [Growthcraft Fishtrap] (growthcraft-1.7.10-2.6.3-complete--d923af5.jar) 
    UCHIJ   Growthcraft|Bamboo{1.7.10-2.6.3} [Growthcraft Bamboo] (growthcraft-1.7.10-2.6.3-complete--d923af5.jar) 
    UCHIJ   hardcorewither{1.1.3} [Hardcore Wither] (Hardcore Wither-1.7.10-1.1.3-21-universal.jar) 
    UCHIJ   HardcoreDarkness{1.7} [Hardcore Darkness] (HardcoreDarkness-MC1.7.10-1.7.jar) 
    UCHIJ   HardcoreEnderExpansion{1.8.6} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.6.jar) 
    UCHIJ   HelpFixer{1.0.7} [HelpFixer] (HelpFixer-1.0.7.jar) 
    UCHIJ   immersiveintegration{0.6.8} [Immersive Integration] (immersiveintegration-0.6.8.jar) 
    UCHIJ   inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
    UCHIJ   LavaMonsters{2.2.1} [Lava Monsters] (LavaMonsters-1.7.10-2.2.1.jar) 
    UCHIJ   LingeringLoot{1.0} [LingeringLoot] (LingeringLoot-1.7.10-2.5.jar) 
    UCHIJ   lootplusplus{0.24_for_1.7} [Loot++] (Loot++-0.24_for_1.7.jar) 
    UCHIJ   LostBooks{1.2.2} [Lost Books] (LostBooks-1.7.10-1.2.2.jar) 
    UCHIJ   MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
    UCHIJ   MobProperties{1.0.2} [Mob Properties] (MobProperties-1.7.10-1.0.2.jar) 
    UCHIJ   modtweaker2{0.9.6} [Mod Tweaker 2] (ModTweaker2-0.9.6.jar) 
    UCHIJ   MusicFix{0.2} [Music Fix] (MusicFix-0.2.zip) 
    UCHIJ   MutantCreatures{1.4.9} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.9.jar) 
    UCHIJ   neiintegration{1.1.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.2.jar) 
    UCHIJ   netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.7.10-1.1.0.jar) 
    UCHIJ   OpenComputers{1.6.0.7-rc.1} [OpenComputers] (OpenComputers-MC1.7.10-1.6.0.7-rc.1-universal.jar) 
    UCHIJ   oretweaker{1.0.2} [Ore Tweaker] (OreTweaker-1.0.2-1.7.10.jar) 
    UCHIJ   PaintingsMod{1.7.2} [Paintings++] (Paintings++-1.7.2_1.3.jar) 
    UCHIJ   ResourceLoader{1.3} [Resource Loader] (ResourceLoader-MC1.7.10-1.3.jar) 
    UCHIJ   Roguelike{1.5.0} [Roguelike Dungeons] (roguelike-1.7.10-1.5.0b.jar) 
    UCHIJ   cuchaz.cuchazinteractive{1.7.10-1.0} [Cuchaz Interactive] (shipsMod-v1.7.10-1.0.4.jar) 
    UCHIJ   cuchaz.ships{1.7.10-1.0.3} [Ships Mod] (shipsMod-v1.7.10-1.0.4.jar) 
    UCHIJ   SpecialAI{1.1.2} [Special AI] (SpecialAI-1.7.10-1.1.2.jar) 
    UCHIJ   SpecialMobs{3.2.2} [Special Mobs] (SpecialMobs-1.7.10-3.2.2.jar) 
    UCHIJ   SpiceOfLife{1.3.5} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.3.5.jar) 
    UCHIJ   sprinkles_for_vanilla{1.6.0} [sprinkles_for_vanilla] (sprinklesforvanilla-1.7.10-1.6.0.jar) 
    UCHIJ   squidless{0.6.1} [Squidless] (squidless-1.7.10-0.6.1.jar) 
    UCHIJ   bq_standard{1.0.99} [Standard Expansion] (StandardExpansion-1.0.99.jar) 
    UCHIJ   StorageDrawers{1.7.10-1.10.2} [Storage Drawers] (StorageDrawers-1.7.10-1.10.2.jar) 
    UCHIJ   ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects] (ThaumcraftMobAspects-1.7.2-2A.jar) 
    UCHIJ   thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a-client.jar) 
    UCHIJ   thebetweenlands{1.0.6-alpha} [The Betweenlands] (TheBetweenlands-1.0.6-alpha-universal.jar) 
    UCHIJ   underphangables{1.0.1} [Underp Hangables] (underphangables-1.7.10-1.0.1.jar) 
    UCHIJ   wailaevents{1.0.0} [Waila Events] (WailaEvents-1.0.0.jar) 
    UCHIJ   waila-blacklist{0.1} [WAILA Blacklist] (waila-blacklist-1.7.10-0.1.jar) 
    UCHIJ   witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
    UCHIJ   YABM2{2.0} [Yet Another Backup Mod 2] (YABM2-1.7.10-2.0.4a.jar) 
    UCHIJ   aobd{2.9.2} [Another One Bites The Dust] (AOBD-2.9.2.jar) 
    UCHIJ   HungerOverhaul{1.7.10-1.0.0.DEV.GITBORK} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.DEV.GITBORK.jar) 
    UCHIJ   UniDict{1.7.10-2.9.1} [UniDict] (UniDict-1.7.10-2.9.1.jar) 
    UD  BiomeTweakerCore{1.2.128} [BiomeTweaker Core] (minecraft.jar) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.22' Renderer: 'GeForce GTX 870M/PCIe/SSE2'
    CoFHCore: -[1.7.10]3.1.3-327
    ThermalFoundation: -[1.7.10]1.2.5-115
    Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
    Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 870M/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.22, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Anisotropic Filtering: Off (1)

```

**Comment by IceDragon200** [comment]
@bloche14 Made a mistake with the recipe class, I've fixed it now, and uploading a new build

**Comment by bloche1871** [comment]
@IceDragon200 I now see recipes to transfer honey from bottles to buckets (and from one bucket to another?), but still no way to make young mead unfortunately

**Comment by IceDragon200** [comment]
@bloche14 The recipes for mead are there, 
(3 honey bottles OR 1 bucket of honey (growthcraft honey)) + (water bottle OR water bucket) + (3 empty bottles OR 1 empty bucket) = (3 bottles of young honey must OR 1 bucket of young honey must)

They probably won't show up in NEI since it's a customer IRecipe

**Comment by bloche1871** [comment]
@IceDragon200 ah, it did not show up in NEI, and when I tried it I didn't think of adding a third empty bucket, thanks!
