### ISSUE TITLE
crash, using bone meal on apple block

### ISSUE THREAD

**Issue by SirSteev** [GrowthcraftCE/Growthcraft-1.7#455]
[21:22:13] [Client thread/INFO]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 3/19/18 9:22 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: squeek.applecore.api.IAppleCoreDispatcher.announcePlantGrowth(Lnet/minecraft/block/Block;Lnet/minecraft/world/World;IIII)V
	at growthcraft.core.integration.AppleCore.announceGrowthTick_AC(AppleCore.java:49)
	at growthcraft.core.integration.AppleCore.announceGrowthTick(AppleCore.java:55)
	at growthcraft.apples.common.block.BlockApple.incrementGrowth(BlockApple.java:71)
	at growthcraft.apples.common.block.BlockApple.func_149853_b(BlockApple.java:97)
	at net.minecraft.item.ItemDye.applyBonemeal(ItemDye.java:167)
	at net.minecraft.item.ItemDye.func_77648_a(ItemDye.java:65)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4332686824 bytes (4131 MB) / 6366953472 bytes (6072 MB) up to 6366953472 bytes (6072 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144M -Xms6144M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 60 mods loaded, 60 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.4.105} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.105-universal.jar) 
	UCHIJAAAA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	cuchaz.ships.core{1.7.10-1.0.2} [Ships Mod Core] (minecraft.jar) 
	UCHIJAAAA	AncientWarfare{2.4.114-beta-MC1.7.10} [Ancient Warfare Core] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
	UCHIJAAAA	AncientWarfareAutomation{2.4.114-beta-MC1.7.10} [Ancient Warfare Automation] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	AncientWarfareNEIPlugin{2.4.114-beta-MC1.7.10} [Ancient Warfare NEI Plugin] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	AncientWarfareNpc{2.4.114-beta-MC1.7.10} [Ancient Warfare NPCs] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	AncientWarfareStructure{2.4.114-beta-MC1.7.10} [Ancient Warfare Structures] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	Artifacts{1.1.1} [Artifacts] (Artifacts-1.1.1.jar) 
	UCHIJAAAA	BiblioCraft{1.10.3} [BiblioCraft] (BiblioCraft[v1.10.3][MC1.7.10].jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar) 
	UCHIJAAAA	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	chisel{2.3.10.37} [Chisel 2] (Chisel2-2.3.10.37.jar) 
	UCHIJAAAA	CraftHeraldry{1.1.3} [CraftHeraldry] (CraftHeraldry 1.1.3.jar) 
	UCHIJAAAA	GraveStone{2.12.2} [GraveStone] (GraveStone-2.12.2.jar) 
	UCHIJAAAA	Growthcraft{1.7.10-2.7.2} [Growthcraft] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UCHIJAAAA	Growthcraft|Cellar{1.7.10-2.7.2} [Growthcraft Cellar] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UCHIJAAAA	Growthcraft|Apples{1.7.10-2.7.2} [Growthcraft Apples] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UCHIJAAAA	Growthcraft|Bamboo{1.7.10-2.7.2} [Growthcraft Bamboo] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UCHIJAAAA	Growthcraft|Bees{1.7.10-2.7.2} [Growthcraft Bees] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UCHIJAAAA	Growthcraft|Fishtrap{1.7.10-2.7.2} [Growthcraft Fishtrap] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UCHIJAAAA	Growthcraft|Grapes{1.7.10-2.7.2} [Growthcraft Grapes] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UCHIJAAAA	Growthcraft|Hops{1.7.10-2.7.2} [Growthcraft Hops] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UCHIJAAAA	Growthcraft|Milk{1.7.10-2.7.2} [Growthcraft Milk] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UCHIJAAAA	Growthcraft|Rice{1.7.10-2.7.2} [Growthcraft Rice] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	Mystcraft{0.11.9.03} [Mystcraft] (mystcraft-1.7.10-0.11.9.03.jar) 
	UCHIJAAAA	NEIAddons{1.12.7.21} [NEI Addons] (neiaddons-mc1710-1.12.7.21.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.7.21} [NEI Addons: Applied Energistics 2] (neiaddons-mc1710-1.12.7.21.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.7.21} [NEI Addons: Botany] (neiaddons-mc1710-1.12.7.21.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.7.21} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.7.21.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.7.21} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.7.21.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.7.21} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.7.21.jar) 
	UCHIJAAAA	neiintegration{1.0.9} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.9.jar) 
	UCHIJAAAA	NetherOres{1.7.10R2.3.1} [Nether Ores] (NetherOres-[1.7.10]2.3.1-22.jar) 
	UCHIJAAAA	notenoughkeys{@MOD_VERSION@} [NotEnoughKEys] (NotEnoughKeys-1.7.10-1.0.0b29.jar) 
	UCHIJAAAA	neresources{0.1.0.95} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0.95.jar) 
	UCHIJAAAA	harvestcraft{1.7.10g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10h.jar) 
	UCHIJAAAA	cuchaz.cuchazinteractive{1.7.10-1.0} [Cuchaz Interactive] (shipsMod-v1.7.10-1.0.2.jar) 
	UCHIJAAAA	cuchaz.ships{1.7.10-1.0.2} [Ships Mod] (shipsMod-v1.7.10-1.0.2.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	thaumcraftneiplugin{1.7.10-1.7} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7.jar) 
	UCHIJAAAA	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-491.jar) 
	UCHIJAAAA	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-37.jar) 
	UCHIJAAAA	TMechworks{0.2.14.100} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.14.100.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) 
	UCHIJAAAA	HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	CoFHCore: -[1.7.10]3.1.2-325
	Mantle Environment: Environment healthy.
	NetherOres: -[1.7.10]2.3.1-22
	TConstruct Environment: Environment healthy.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['steev121'/286, l='New Worl', x=260.55, y=64.00, z=-137.84]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by SirSteev** [comment]
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 3/19/18 9:35 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: squeek.applecore.api.IAppleCoreDispatcher.announcePlantGrowth(Lnet/minecraft/block/Block;Lnet/minecraft/world/World;IIII)V
	at growthcraft.core.integration.AppleCore.announceGrowthTick_AC(AppleCore.java:49)
	at growthcraft.core.integration.AppleCore.announceGrowthTick(AppleCore.java:55)
	at growthcraft.apples.common.block.BlockApple.incrementGrowth(BlockApple.java:71)
	at growthcraft.apples.common.block.BlockApple.func_149853_b(BlockApple.java:97)
	at net.minecraft.item.ItemDye.applyBonemeal(ItemDye.java:167)
	at net.minecraft.item.ItemDye.func_77648_a(ItemDye.java:65)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by IceDragon200** [comment]
Are you Running Apple Core < 1.3 (is the version older than 1.3?), if so then upgrade to the latest Apple Core for Minecraft 1.7.10.

Let me know if the problem persists

**Comment by SirSteev** [comment]
resolved, good eye.
